// Local starter catalogue. Nutritional values are approximate per listed portion,
// so users can always adjust the amount before saving an entry.
const f = (id, sr, en, de, category, portion, unit, calories, proteinG, carbsG, fatG, allergens = []) => ({
  id, names: { sr, en, de }, category, portion, unit, calories, proteinG, carbsG, fatG, allergens, estimated: true
});

export const FOOD_LIBRARY_CATEGORIES = [
  { id: 'protein', labels: { sr: 'Proteini', en: 'Protein', de: 'Protein' } },
  { id: 'dairy', labels: { sr: 'Mliječni proizvodi', en: 'Dairy', de: 'Milchprodukte' } },
  { id: 'grains', labels: { sr: 'Žitarice i hljeb', en: 'Grains & bread', de: 'Getreide & Brot' } },
  { id: 'fruit-veg', labels: { sr: 'Voće i povrće', en: 'Fruit & vegetables', de: 'Obst & Gemüse' } },
  { id: 'fats', labels: { sr: 'Masti i orašasti plodovi', en: 'Fats & nuts', de: 'Fette & Nüsse' } },
  { id: 'meals', labels: { sr: 'Jednostavni obroci', en: 'Simple meals', de: 'Einfache Mahlzeiten' } },
  { id: 'drinks', labels: { sr: 'Pića', en: 'Drinks', de: 'Getränke' } },
  { id: 'snacks', labels: { sr: 'Užine i slatko', en: 'Snacks & sweets', de: 'Snacks & Süßes' } }
];

export const FOOD_LIBRARY = [
  // Protein
  f('chicken-breast','Pileća prsa','Chicken breast','Hähnchenbrust','protein',100,'g',165,31,0,3.6),
  f('chicken-thigh','Pileći batak bez kože','Skinless chicken thigh','Hähnchenschenkel ohne Haut','protein',100,'g',177,24,0,8.2),
  f('turkey-breast','Ćureća prsa','Turkey breast','Putenbrust','protein',100,'g',135,29,0,1.6),
  f('beef-lean','Nemasna junetina','Lean beef','Mageres Rindfleisch','protein',100,'g',195,27,0,8),
  f('beef-mince','Mljevena junetina','Ground beef','Rinderhackfleisch','protein',100,'g',250,26,0,17),
  f('pork-loin','Svinjski file','Pork loin','Schweinefilet','protein',100,'g',143,26,0,3.5),
  f('tuna-water','Tuna u vodi','Tuna in water','Thunfisch in Wasser','protein',100,'g',116,26,0,1),
  f('salmon','Losos','Salmon','Lachs','protein',100,'g',208,20,0,13),
  f('trout','Pastrmka','Trout','Forelle','protein',100,'g',148,20,0,6),
  f('sardines','Sardine','Sardines','Sardinen','protein',100,'g',208,25,0,11),
  f('shrimp','Kozice','Shrimp','Garnelen','protein',100,'g',99,24,0.2,0.3),
  f('egg','Jaje','Egg','Ei','protein',1,'komad',72,6.3,0.4,4.8,['eggs']),
  f('egg-whites','Bjelanca','Egg whites','Eiweiß','protein',100,'g',52,11,0.7,0.2,['eggs']),
  f('tofu','Tofu','Tofu','Tofu','protein',100,'g',144,15,3,8,['soy']),
  f('tempeh','Tempeh','Tempeh','Tempeh','protein',100,'g',193,20,8,11,['soy']),
  f('seitan','Seitan','Seitan','Seitan','protein',100,'g',141,25,12,2,['gluten']),
  f('lentils-cooked','Kuhana leća','Cooked lentils','Gekochte Linsen','protein',100,'g',116,9,20,0.4),
  f('chickpeas-cooked','Kuhani slanutak','Cooked chickpeas','Gekochte Kichererbsen','protein',100,'g',164,9,27,2.6),
  f('beans-cooked','Kuhani grah','Cooked beans','Gekochte Bohnen','protein',100,'g',127,8.7,23,0.5),
  f('protein-powder','Whey protein','Whey protein','Whey-Protein','protein',30,'g',120,24,3,1.5,['milk']),
  // Dairy
  f('greek-yogurt','Grčki jogurt','Greek yogurt','Griechischer Joghurt','dairy',150,'g',146,15,5,6,['milk']),
  f('skyr','Skyr','Skyr','Skyr','dairy',150,'g',94,16,6,0.3,['milk']),
  f('cottage-cheese','Posni sir','Cottage cheese','Hüttenkäse','dairy',100,'g',98,11,3.4,4.3,['milk']),
  f('lowfat-quark','Nemasni quark','Low-fat quark','Magerquark','dairy',100,'g',67,12,4,0.2,['milk']),
  f('milk','Mlijeko','Milk','Milch','dairy',250,'ml',153,8.3,12,8.3,['milk']),
  f('lowfat-milk','Mlijeko 1.5%','Low-fat milk','Fettarme Milch','dairy',250,'ml',118,8.5,12,3.8,['milk']),
  f('kefir','Kefir','Kefir','Kefir','dairy',250,'ml',130,8.5,12,6.3,['milk']),
  f('plain-yogurt','Obični jogurt','Plain yogurt','Naturjoghurt','dairy',180,'g',110,6,8,5,['milk']),
  f('mozzarella','Mozzarella','Mozzarella','Mozzarella','dairy',100,'g',280,22,3,20,['milk']),
  f('feta','Feta sir','Feta cheese','Feta','dairy',50,'g',132,7,2,11,['milk']),
  f('hard-cheese','Tvrdi sir','Hard cheese','Hartkäse','dairy',30,'g',120,8,0.5,10,['milk']),
  f('cream-cheese','Krem sir','Cream cheese','Frischkäse','dairy',30,'g',75,2,1.5,7,['milk']),
  f('buttermilk','Mlaćenica','Buttermilk','Buttermilch','dairy',250,'ml',98,8,12,1.5,['milk']),
  f('protein-pudding','Proteinski puding','Protein pudding','Proteinpudding','dairy',200,'g',150,20,10,3,['milk']),
  f('ice-cream','Sladoled','Ice cream','Eiscreme','dairy',100,'g',207,3.5,24,11,['milk']),
  // Grains and bread
  f('oats','Zobene pahuljice','Oats','Haferflocken','grains',50,'g',185,6.5,31,3.5,['gluten']),
  f('rice-cooked','Kuhana riža','Cooked rice','Gekochter Reis','grains',150,'g',195,4,42,0.5),
  f('brown-rice-cooked','Kuhana smeđa riža','Cooked brown rice','Gekochter Vollkornreis','grains',150,'g',167,3.9,35,1.4),
  f('pasta-cooked','Kuhana tjestenina','Cooked pasta','Gekochte Nudeln','grains',150,'g',237,8.7,46,1.4,['gluten']),
  f('wholewheat-pasta','Integralna tjestenina','Whole-wheat pasta','Vollkornnudeln','grains',150,'g',224,9,43,1.8,['gluten']),
  f('bread-white','Bijeli hljeb','White bread','Weißbrot','grains',60,'g',159,5.3,30,1.9,['gluten']),
  f('bread-wholegrain','Integralni hljeb','Wholegrain bread','Vollkornbrot','grains',60,'g',148,5.5,25,2.2,['gluten']),
  f('tortilla','Tortilja','Tortilla wrap','Tortilla','grains',60,'g',190,5,32,4,['gluten']),
  f('potato-boiled','Kuhani krompir','Boiled potato','Gekochte Kartoffel','grains',200,'g',174,4,40,0.2),
  f('sweet-potato','Slatki krompir','Sweet potato','Süßkartoffel','grains',200,'g',172,3.2,40,0.2),
  f('couscous','Kuhani kus-kus','Cooked couscous','Gekochter Couscous','grains',150,'g',168,5.7,35,0.3,['gluten']),
  f('bulgur','Kuhani bulgur','Cooked bulgur','Gekochter Bulgur','grains',150,'g',125,4.7,28,0.3,['gluten']),
  f('polenta','Kuhana palenta','Cooked polenta','Gekochte Polenta','grains',200,'g',140,3,30,0.4),
  f('cornflakes','Kukuruzne pahuljice','Cornflakes','Cornflakes','grains',40,'g',143,3,33,0.2,['gluten']),
  f('muesli','Musli','Muesli','Müsli','grains',60,'g',222,6,39,5,['gluten','nuts']),
  f('rice-cakes','Rižini krekeri','Rice cakes','Reiswaffeln','grains',3,'komad',105,2.1,23,0.9),
  f('bagel','Pecivo bagel','Bagel','Bagel','grains',1,'komad',270,10,53,1.7,['gluten']),
  f('croissant','Kroasan','Croissant','Croissant','grains',1,'komad',231,5,26,12,['gluten','milk','eggs']),
  f('pizza-dough','Tijesto za pizzu','Pizza dough','Pizzateig','grains',150,'g',390,12,78,4,['gluten']),
  f('flour','Pšenično brašno','Wheat flour','Weizenmehl','grains',100,'g',364,10,76,1,['gluten']),
  // Fruit and vegetables
  f('banana','Banana','Banana','Banane','fruit-veg',1,'komad',105,1.3,27,0.4),
  f('apple','Jabuka','Apple','Apfel','fruit-veg',1,'komad',95,0.5,25,0.3),
  f('orange','Narandža','Orange','Orange','fruit-veg',1,'komad',62,1.2,15,0.2),
  f('pear','Kruška','Pear','Birne','fruit-veg',1,'komad',101,0.6,27,0.2),
  f('strawberries','Jagode','Strawberries','Erdbeeren','fruit-veg',150,'g',48,1,11.5,0.5),
  f('blueberries','Borovnice','Blueberries','Blaubeeren','fruit-veg',100,'g',57,0.7,14,0.3),
  f('raspberries','Maline','Raspberries','Himbeeren','fruit-veg',100,'g',52,1.2,12,0.7),
  f('grapes','Grožđe','Grapes','Trauben','fruit-veg',150,'g',104,1.1,27,0.2),
  f('watermelon','Lubenica','Watermelon','Wassermelone','fruit-veg',300,'g',90,1.8,23,0.5),
  f('peach','Breskva','Peach','Pfirsich','fruit-veg',1,'komad',59,1.4,14,0.4),
  f('kiwi','Kivi','Kiwi','Kiwi','fruit-veg',2,'komad',84,1.6,20,0.8),
  f('avocado','Avokado','Avocado','Avocado','fruit-veg',100,'g',160,2,9,15),
  f('tomato','Paradajz','Tomato','Tomate','fruit-veg',150,'g',27,1.3,5.8,0.3),
  f('cucumber','Krastavac','Cucumber','Gurke','fruit-veg',150,'g',23,1,5.4,0.2),
  f('pepper','Paprika','Bell pepper','Paprika','fruit-veg',150,'g',47,1.5,9,0.5),
  f('carrot','Mrkva','Carrot','Karotte','fruit-veg',100,'g',41,0.9,10,0.2),
  f('broccoli','Brokoli','Broccoli','Brokkoli','fruit-veg',150,'g',51,4.2,10,0.6),
  f('cauliflower','Karfiol','Cauliflower','Blumenkohl','fruit-veg',150,'g',38,3,7.5,0.5),
  f('spinach','Špinat','Spinach','Spinat','fruit-veg',100,'g',23,2.9,3.6,0.4),
  f('zucchini','Tikvica','Zucchini','Zucchini','fruit-veg',150,'g',26,1.8,4.7,0.5),
  f('mushrooms','Gljive','Mushrooms','Champignons','fruit-veg',150,'g',33,4.7,5,0.5),
  f('onion','Luk','Onion','Zwiebel','fruit-veg',100,'g',40,1.1,9.3,0.1),
  f('lettuce','Zelena salata','Lettuce','Kopfsalat','fruit-veg',100,'g',15,1.4,2.9,0.2),
  f('cabbage','Kupus','Cabbage','Kohl','fruit-veg',150,'g',38,2,9,0.2),
  f('peas','Grašak','Peas','Erbsen','fruit-veg',150,'g',122,8,22,0.6),
  // Fats and nuts
  f('olive-oil','Maslinovo ulje','Olive oil','Olivenöl','fats',10,'ml',90,0,0,10),
  f('butter','Maslac','Butter','Butter','fats',10,'g',72,0.1,0,8.1,['milk']),
  f('peanut-butter','Maslac od kikirikija','Peanut butter','Erdnussbutter','fats',20,'g',118,5,4,10,['peanuts']),
  f('almonds','Bademi','Almonds','Mandeln','fats',30,'g',174,6.4,6.5,15,['nuts']),
  f('walnuts','Orasi','Walnuts','Walnüsse','fats',30,'g',196,4.6,4.1,19.6,['nuts']),
  f('cashews','Indijski orah','Cashews','Cashewkerne','fats',30,'g',166,5.5,9,13,['nuts']),
  f('hazelnuts','Lješnjaci','Hazelnuts','Haselnüsse','fats',30,'g',188,4.5,5,18,['nuts']),
  f('pumpkin-seeds','Sjemenke bundeve','Pumpkin seeds','Kürbiskerne','fats',30,'g',168,9,3,14,['seeds']),
  f('chia-seeds','Chia sjemenke','Chia seeds','Chiasamen','fats',15,'g',73,2.5,6,4.6,['seeds']),
  f('flax-seeds','Lanene sjemenke','Flax seeds','Leinsamen','fats',15,'g',80,2.7,4.3,6.3,['seeds']),
  f('sunflower-seeds','Suncokretove sjemenke','Sunflower seeds','Sonnenblumenkerne','fats',30,'g',175,6,6,15,['seeds']),
  f('mayonnaise','Majoneza','Mayonnaise','Mayonnaise','fats',15,'g',100,0.2,0.2,11,['eggs']),
  f('pesto','Pesto','Pesto','Pesto','fats',30,'g',140,3,3,13,['nuts','milk']),
  f('dark-chocolate','Tamna čokolada','Dark chocolate','Dunkle Schokolade','fats',25,'g',150,2,12,10),
  f('coconut-milk','Kokosovo mlijeko','Coconut milk','Kokosmilch','fats',100,'ml',185,2,3,18),
  // Simple meals
  f('chicken-rice','Piletina i riža','Chicken and rice','Hähnchen mit Reis','meals',1,'porcija',620,48,73,14),
  f('chicken-potato','Piletina i krompir','Chicken and potatoes','Hähnchen mit Kartoffeln','meals',1,'porcija',580,48,58,16),
  f('tuna-sandwich','Sendvič s tunom','Tuna sandwich','Thunfischsandwich','meals',1,'porcija',430,30,45,14,['gluten','fish']),
  f('eggs-toast','Jaja i tost','Eggs and toast','Eier mit Toast','meals',1,'porcija',390,23,31,19,['eggs','gluten']),
  f('oatmeal-protein','Zobena kaša s proteinom','Protein oatmeal','Protein-Porridge','meals',1,'porcija',440,33,55,10,['gluten','milk']),
  f('yogurt-fruit','Jogurt i voće','Yogurt and fruit','Joghurt mit Obst','meals',1,'porcija',280,17,36,7,['milk']),
  f('pasta-bolognese','Tjestenina bolonjez','Pasta bolognese','Pasta Bolognese','meals',1,'porcija',680,38,75,24,['gluten']),
  f('pasta-tuna','Tjestenina s tunom','Tuna pasta','Thunfischpasta','meals',1,'porcija',590,40,74,13,['gluten','fish']),
  f('omelette','Omlet sa povrćem','Vegetable omelette','Gemüseomelett','meals',1,'porcija',330,24,10,21,['eggs']),
  f('chili-con-carne','Chili con carne','Chili con carne','Chili con Carne','meals',1,'porcija',560,38,57,18),
  f('bean-stew','Grah','Bean stew','Bohneneintopf','meals',1,'porcija',420,20,63,10),
  f('lentil-stew','Leća','Lentil stew','Linseneintopf','meals',1,'porcija',390,23,58,7),
  f('cevapi','Ćevapi','Ćevapi','Ćevapi','meals',10,'komada',650,38,20,45),
  f('burek','Burek','Burek','Burek','meals',1,'porcija',720,23,65,40,['gluten','milk']),
  f('pita-cheese','Sirnica','Cheese pie','Käsepita','meals',1,'porcija',600,21,50,34,['gluten','milk']),
  f('pizza-margherita','Pizza Margherita','Margherita pizza','Pizza Margherita','meals',1,'porcija',720,28,92,27,['gluten','milk']),
  f('pizza-chicken','Pizza s piletinom','Chicken pizza','Hähnchenpizza','meals',1,'porcija',760,39,88,28,['gluten','milk']),
  f('burger','Burger','Burger','Burger','meals',1,'komad',650,32,45,38,['gluten','milk']),
  f('grilled-fish','Riba sa salatom','Fish with salad','Fisch mit Salat','meals',1,'porcija',420,38,18,22,['fish']),
  f('risotto-chicken','Rižoto s piletinom','Chicken risotto','Hähnchenrisotto','meals',1,'porcija',590,39,73,14),
  f('wrap-chicken','Tortilja s piletinom','Chicken wrap','Hähnchen-Wrap','meals',1,'porcija',530,35,54,18,['gluten']),
  f('sandwich-turkey','Sendvič s ćuretinom','Turkey sandwich','Putensandwich','meals',1,'porcija',440,31,46,12,['gluten']),
  f('salad-chicken','Salata s piletinom','Chicken salad','Hähnchensalat','meals',1,'porcija',410,40,18,19),
  f('salad-tuna','Salata s tunom','Tuna salad','Thunfischsalat','meals',1,'porcija',390,34,15,20,['fish']),
  f('vegan-bowl','Veganska zdjela','Vegan bowl','Vegane Bowl','meals',1,'porcija',540,20,78,17),
  // Drinks
  f('water','Voda','Water','Wasser','drinks',250,'ml',0,0,0,0),
  f('coffee-black','Crna kafa','Black coffee','Schwarzer Kaffee','drinks',1,'šolja',2,0.3,0,0),
  f('coffee-milk','Kafa s mlijekom','Coffee with milk','Kaffee mit Milch','drinks',1,'šolja',65,3,6,3,['milk']),
  f('tea','Čaj bez šećera','Unsweetened tea','Ungesüßter Tee','drinks',250,'ml',2,0,0.5,0),
  f('orange-juice','Sok od narandže','Orange juice','Orangensaft','drinks',250,'ml',112,1.7,26,0.5),
  f('cola','Cola','Cola','Cola','drinks',330,'ml',139,0,35,0),
  f('cola-zero','Cola zero','Diet cola','Cola Zero','drinks',330,'ml',1,0,0,0),
  f('energy-drink','Energetsko piće','Energy drink','Energy-Drink','drinks',250,'ml',110,0,27,0),
  f('beer','Pivo','Beer','Bier','drinks',500,'ml',215,2,18,0),
  f('wine','Vino','Wine','Wein','drinks',150,'ml',125,0,4,0),
  f('rakija','Rakija','Fruit brandy','Rakija','drinks',50,'ml',110,0,0,0),
  f('smoothie-fruit','Voćni smoothie','Fruit smoothie','Frucht-Smoothie','drinks',300,'ml',190,3,43,1),
  f('protein-shake','Proteinski šejk','Protein shake','Proteinshake','drinks',300,'ml',220,30,15,5,['milk']),
  f('hot-chocolate','Topla čokolada','Hot chocolate','Heiße Schokolade','drinks',250,'ml',210,8,32,7,['milk']),
  f('lemonade','Limunada','Lemonade','Limonade','drinks',250,'ml',90,0,22,0),
  // Snacks and sweets
  f('protein-bar','Proteinska pločica','Protein bar','Proteinriegel','snacks',1,'komad',210,20,18,7,['milk','nuts']),
  f('granola-bar','Musli pločica','Granola bar','Müsliriegel','snacks',1,'komad',160,3,25,5,['gluten','nuts']),
  f('chips','Čips','Potato chips','Kartoffelchips','snacks',50,'g',268,3,26,17),
  f('popcorn','Kokice','Popcorn','Popcorn','snacks',30,'g',116,3.5,22,1.3),
  f('pretzels','Slani štapići','Pretzels','Salzstangen','snacks',50,'g',190,5,38,1.5,['gluten']),
  f('biscuits','Keks','Biscuits','Kekse','snacks',50,'g',240,3,34,11,['gluten','milk','eggs']),
  f('waffles','Vafli','Wafers','Waffeln','snacks',40,'g',210,2,25,12,['gluten','milk']),
  f('milk-chocolate','Mliječna čokolada','Milk chocolate','Milchschokolade','snacks',40,'g',214,3,23,13,['milk']),
  f('gummy-candy','Gumene bombone','Gummy candy','Gummibärchen','snacks',50,'g',170,3,39,0),
  f('donut','Krofna','Donut','Donut','snacks',1,'komad',290,4,35,15,['gluten','milk','eggs']),
  f('cake','Kolač','Cake','Kuchen','snacks',1,'komad',350,5,45,17,['gluten','milk','eggs']),
  f('baklava','Baklava','Baklava','Baklava','snacks',1,'komad',230,3,28,12,['gluten','nuts']),
  f('jam','Džem','Jam','Marmelade','snacks',20,'g',52,0,13,0),
  f('honey','Med','Honey','Honig','snacks',20,'g',61,0,17,0),
  f('dates','Hurme','Dates','Datteln','snacks',40,'g',113,1,30,0),
  f('dried-fruit','Suho voće','Dried fruit','Trockenfrüchte','snacks',40,'g',120,1,30,0),
  f('rice-pudding','Riža na mlijeku','Rice pudding','Milchreis','snacks',200,'g',260,8,46,5,['milk']),
  f('pancakes','Palačinke','Pancakes','Pfannkuchen','snacks',2,'komada',340,10,48,12,['gluten','milk','eggs'])
,
  // Balkanska svakodnevna i tradicionalna jela. Vrijednosti su procjene po porciji.
  f('burek-meat','Burek s mesom','Meat burek','Burek mit Fleisch','meals',1,'porcija',720,24,64,41,['gluten']),
  f('zeljanica','Zeljanica','Spinach pie','Spinat-B\u00f6rek','meals',1,'porcija',560,17,52,31,['gluten','milk','eggs']),
  f('krompirusa','Krompiru\u0161a','Potato pie','Kartoffel-B\u00f6rek','meals',1,'porcija',540,11,66,25,['gluten']),
  f('tikvenica','Tikvenica','Pumpkin pie','K\u00fcrbispita','meals',1,'porcija',420,9,58,17,['gluten','milk','eggs']),
  f('apple-pie-balkan','Pita s jabukama','Balkan apple pie','Apfelpita','snacks',1,'porcija',390,5,58,15,['gluten']),
  f('gibanica','Gibanica','Serbian cheese pie','Serbische K\u00e4sepita','meals',1,'porcija',650,22,47,41,['gluten','milk','eggs']),
  f('pita-mushroom','Pita s gljivama','Mushroom pie','Pilz-B\u00f6rek','meals',1,'porcija',480,13,53,23,['gluten','milk']),
  f('pita-chicken','Pita s piletinom','Chicken pie','H\u00e4hnchen-B\u00f6rek','meals',1,'porcija',610,26,55,31,['gluten','milk']),
  f('proja','Proja','Cornbread','Maisbrot','grains',1,'komad',210,5,31,8,['eggs','milk']),
  f('ustipci','U\u0161tipci','Fried dough fritters','Teigkrapfen','snacks',3,'komada',380,8,48,17,['gluten','milk','eggs']),
  f('pogaca','Poga\u010da','Balkan flatbread','Balkanisches Fladenbrot','grains',100,'g',275,8,54,3,['gluten']),
  f('somun','Somun','Bosnian flatbread','Bosnisches Fladenbrot','grains',1,'komad',260,8,52,2,['gluten']),
  f('kajmak','Kajmak','Clotted cream spread','Kajmak','dairy',30,'g',180,2,1,18,['milk']),
  f('ajvar','Ajvar','Roasted pepper spread','Paprikaaufstrich','fruit-veg',30,'g',45,1,5,3),
  f('pinjur','Pin\u0111ur','Roasted vegetable spread','Ger\u00f6steter Gem\u00fcseaufstrich','fruit-veg',30,'g',38,1,5,2),
  f('chicken-soup','Pile\u0107a supa','Chicken soup','H\u00fchnersuppe','meals',1,'tanjir',150,12,12,5,['gluten','eggs']),
  f('beef-soup','Tele\u0107a \u010dorba','Veal soup','Kalbfleischsuppe','meals',1,'tanjir',240,20,14,10,['gluten']),
  f('begova-corba','Begova \u010dorba','Begova soup','Begova-Suppe','meals',1,'tanjir',310,24,18,14,['gluten','eggs']),
  f('bean-soup','Grah \u010dorba','Bean soup','Bohnensuppe','meals',1,'tanjir',330,16,45,9),
  f('fish-soup','Riblja \u010dorba','Fish soup','Fischsuppe','meals',1,'tanjir',210,22,13,7,['fish']),
  f('vegetable-soup','Povrtna supa','Vegetable soup','Gem\u00fcsesuppe','meals',1,'tanjir',120,5,18,3),
  f('mushroom-soup','Krem supa od gljiva','Creamy mushroom soup','Champignoncremesuppe','meals',1,'tanjir',220,7,20,12,['milk']),
  f('tarhana-soup','Tarhana','Tarhana soup','Tarhana-Suppe','meals',1,'tanjir',280,12,40,8,['gluten','milk']),
  f('sarma','Sarma','Stuffed cabbage rolls','Kohlrouladen','meals',3,'komada',510,27,40,25),
  f('stuffed-peppers','Punjene paprike','Stuffed peppers','Gef\u00fcllte Paprika','meals',2,'komada',540,30,45,24),
  f('beef-goulash','June\u0107i gula\u0161','Beef goulash','Rindergulasch','meals',1,'porcija',560,36,36,28),
  f('chicken-paprikash','Pile\u0107i paprika\u0161','Chicken paprikash','H\u00e4hnchenpaprikasch','meals',1,'porcija',520,35,30,26,['milk']),
  f('bosnian-pot','Bosanski lonac','Bosnian pot stew','Bosnischer Eintopf','meals',1,'porcija',490,31,41,19),
  f('peas-with-meat','Gra\u0161ak s mesom','Peas with meat','Erbsen mit Fleisch','meals',1,'porcija',470,31,39,16),
  f('moussaka-potato','Musaka s krompirom','Potato moussaka','Kartoffel-Moussaka','meals',1,'porcija',610,30,48,29,['milk','eggs']),
  f('prebranac','Prebranac','Serbian baked beans','Serbische Bohnenpfanne','meals',1,'porcija',410,16,58,12),
  f('pasulj-sausage','Pasulj sa kobasicom','Bean stew with sausage','Bohneneintopf mit Wurst','meals',1,'porcija',590,28,53,27),
  f('cabbage-meat','Kupus s mesom','Cabbage with meat','Kohl mit Fleisch','meals',1,'porcija',440,30,25,22),
  f('stuffed-zucchini','Punjene tikvice','Stuffed zucchini','Gef\u00fcllte Zucchini','meals',2,'komada',420,27,28,20),
  f('baked-beans','Zape\u010deni grah','Baked beans','Gebackene Bohnen','meals',1,'porcija',390,17,55,9),
  f('sataras','Satara\u0161','Pepper and tomato stew','Paprika-Tomaten-Pfanne','meals',1,'porcija',260,9,22,15,['eggs']),
  f('djuvec','\u0110uve\u010d','Balkan vegetable rice','Balkanischer Gem\u00fcsereis','meals',1,'porcija',430,12,68,13),
  f('pljeskavica','Pljeskavica','Balkan burger patty','Balkanisches Hacksteak','meals',1,'komad',520,31,7,41),
  f('sudzukice','Sud\u017eukice','Spicy Balkan sausages','W\u00fcrzige Balkanw\u00fcrste','meals',4,'komada',600,29,5,53),
  f('raznjici','Ra\u017enji\u0107i','Grilled meat skewers','Fleischspie\u00dfe','meals',2,'ra\u017enji\u0107a',470,38,8,29),
  f('mixed-grill','Mije\u0161ano meso','Mixed grill','Gemischter Grillteller','meals',1,'porcija',850,52,24,62),
  f('roast-pork','Pe\u010dena svinjetina','Roast pork','Schweinebraten','meals',200,'g',620,47,0,46),
  f('roast-lamb','Jagnje\u0107e pe\u010denje','Roast lamb','Lammbraten','meals',200,'g',650,48,0,50),
  f('grilled-chicken','Piletina sa ro\u0161tilja','Grilled chicken','Gegrilltes H\u00e4hnchen','meals',1,'porcija',460,48,16,22),
  f('chicken-schnitzel','Pile\u0107i be\u010dki odrezak','Chicken schnitzel','H\u00e4hnchenschnitzel','meals',1,'porcija',610,38,42,31,['gluten','eggs']),
  f('cevapi-somun','\u0106evapi u somunu','\u0106evapi with flatbread','\u0106evapi mit Fladenbrot','meals',10,'komada',880,42,76,45,['gluten']),
  f('grilled-trout','Pastrmka sa ro\u0161tilja','Grilled trout','Gegrillte Forelle','meals',1,'porcija',430,42,8,23,['fish']),
  f('shopska-salad','\u0160opska salata','Shopska salad','Schopska-Salat','meals',1,'porcija',230,9,15,16,['milk']),
  f('serbian-salad','Srpska salata','Serbian salad','Serbischer Salat','meals',1,'porcija',130,3,14,8),
  f('cabbage-salad','Kupus salata','Cabbage salad','Kohlsalat','fruit-veg',1,'porcija',90,2,11,5),
  f('potato-salad','Krompir salata','Potato salad','Kartoffelsalat','meals',1,'porcija',260,5,34,12),
  f('russian-salad','Ruska salata','Russian salad','Russischer Salat','meals',1,'porcija',350,7,27,24,['eggs']),
  f('beans-salad','Grah salata','Bean salad','Bohnensalat','meals',1,'porcija',290,14,37,10),
  f('yogurt-cucumber-salad','Krastavac u jogurtu','Cucumber yogurt salad','Gurkensalat mit Joghurt','meals',1,'porcija',150,7,12,8,['milk']),
  f('polenta-cheese','Palenta sa sirom','Polenta with cheese','Polenta mit K\u00e4se','meals',1,'porcija',390,15,48,15,['milk']),
  f('macaroni-cheese','Makaroni sa sirom','Macaroni and cheese','Makkaroni mit K\u00e4se','meals',1,'porcija',590,24,67,25,['gluten','milk']),
  f('tulumbe','Tulumbe','Syrup-soaked pastries','Tulumben','snacks',3,'komada',360,4,62,11,['gluten','eggs']),
  f('hurmasice','Hurma\u0161ice','Syrup cookies','Hurmasice','snacks',3,'komada',330,4,55,12,['gluten','eggs']),
  f('krempita','Krempita','Cream slice','Cremeschnitte','snacks',1,'komad',380,6,47,19,['gluten','milk','eggs']),
  f('orasnice','Ora\u0161nice','Walnut cookies','Walnusspl\u00e4tzchen','snacks',3,'komada',300,5,28,18,['nuts','eggs']),
  f('strudel-apple','\u0160trudla s jabukama','Apple strudel','Apfelstrudel','snacks',1,'komad',320,4,46,14,['gluten']),
  f('vanilice','Vanilice','Vanilla sandwich cookies','Vanille-Doppelkekse','snacks',3,'komada',290,4,34,15,['gluten','milk','eggs']),
  f('palacinke-jam','Pala\u010dinke s d\u017eemom','Pancakes with jam','Pfannkuchen mit Marmelade','snacks',2,'komada',410,9,64,12,['gluten','milk','eggs']),
  f('palacinke-nutella','Pala\u010dinke s kremom','Chocolate spread pancakes','Pfannkuchen mit Schokocreme','snacks',2,'komada',520,10,65,24,['gluten','milk','eggs','nuts']),
  f('cheesecake','Cheesecake','Cheesecake','K\u00e4sekuchen','snacks',1,'komad',410,7,39,25,['gluten','milk','eggs']),
  f('bombice-coconut','Kokos kuglice','Coconut truffles','Kokoskugeln','snacks',3,'komada',270,3,28,16,['milk'])
];

export function getFoodLibraryName(item, language = 'sr') {
  return item?.names?.[language] || item?.names?.sr || '';
}
